### ISSUE TITLE
customize output

### ISSUE THREAD

**Issue by lorvent** [MeanVJ/Bootstrap-Form-Builder#1]
hi

how can i customize output?

say something like a json response instead of full form code.

**Comment by MEVJ** [comment]
I am working on that currently will post soon...there is library available to convert html to json ....will be using that to convert

**Comment by lorvent** [comment]
Wow

i never knew such library exists, can you tell me library name?

**Comment by MEVJ** [comment]
You can look into below..I am not getting time to work on this ....you can contribute if you are able to do this...
https://github.com/Jxck/html2json

**Comment by lorvent** [comment]
Ok... thanks for link, i will check into it.
